name: CMI
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  rxdart: ^0.27.3
  flutter_native_splash: ^2.2.16
  hexcolor: ^3.0.1
  firebase_core: ^2.16.0
  firebase_auth: ^4.2.4
  google_sign_in: ^5.4.2
  shared_preferences: ^2.0.15
  google_fonts: ^5.1.0
  shared_preferences_foundation: 2.2.2
  #Fixing a bug
  lottie: ^2.3.1
  flutter_overlay_loader: ^1.0.3
  flutter_signin_button: ^2.0.0
  pinput: ^2.2.21
  get: ^4.6.5
  stream_channel: ^2.1.0
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.1.1
  line_awesome_flutter: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/new 1.png"
flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/cefmorsi.png
  image_dark: assets/images/cefmorsi.png

  android_12:
    image: assets/images/new 1.png
    icon_background_color: "#f7f6f1"
    image_dark: assets/images/cefmorsi.png
    icon_background_color_dark: "#272727"

flutter:
  uses-material-design: true
  assets:
    - assets/images/cefmorsilogo.png
    - assets/images/splash-image.png
    - assets/images/splash.png
    - assets/images/apple.jpg
    - assets/images/google.jpg
    - assets/images/gg.png
    - assets/images/apple.png
    - assets/images/splash-top-icon.png
    - assets/images/cefmorsi.png
    - assets/images/new 1.png
    - assets/images/userprofile.jpeg
    - assets/images/dashboard/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
